### ISSUE TITLE
Contact Us Map doesn't show in some browsers

### ISSUE THREAD

**Issue by 123Dragon** [trydalcoholic/opencart-materialize#3]
The Contact us Map doesn't show in Firefox 53.0.3 (32-bit), doesn't work in Microsoft Edge 38.14393.1066.0, seems to work only in Google Chrome browser.

![image](https://cloud.githubusercontent.com/assets/29109935/26682244/c3cd8e3a-46ad-11e7-960a-ee4332a8e335.png)

**Comment by trydalcoholic** [comment]
The problem is in asynchronous loading of the script of the card itself. Fix it quickly:
_catalog/view/theme/materialize/template/information.contact.tpl_ find `<script async src="//api-maps.yandex.ru/2.1/?lang=ru_RU"></script>` and remove `async`.
By default, Yandex.Map is loaded, which is relevant for the CIS region. Therefore, I'll think about a more graceful decision 👌.

**Comment by trydalcoholic** [comment]
With Google maps was a little more difficult, have to postpone them for the future update of the template 😒.
So far, there will be Yandex.Maps.
