### ISSUE TITLE
Apps store 

### ISSUE THREAD

**Issue by hammoudeh** [trydalcoholic/opencart-materialize#64]
Hi, my question is there any one use it in webview with other features such as "Push notification, deep linking ..etc."  and publish it in apps store ?

**Comment by trydalcoholic** [comment]
Hello!
The new version will be published in the app store.
Push notification - there is an idea of use, so that probably will also appear in the future functionality.
Deep linking - I almost have no idea what it is, it seemed to me that this is due to the work of the applications, and not the web site 🤔.
